caso/cakehouse/urls.py
from django.urls import path

from . import views
app_name = 'cakehouse'
urlpatterns = [
    path('', views.index, name='index'),
    path('ver_productos', views.ver_productos, name='ver_productos'),
    path('pagar_productos', views.pagar_productos, name='pagar_productos'),
    path('guardar_pago', views.guardar_pago, name='guardar_pago'),
    path('iniciosesion', views.iniciosesion, name='iniciosesion'),
    path('inicses', views.inicses, name='inicses'),
    path('logoutv', views.logoutv, name='logoutv'),
    path('indexadmin', views.indexadmin, name='indexadmin'),
]

caso/caso/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets
from cakehouse.models import Producto, Pago
from caso import views
from django.conf import settings
from django.conf.urls.static import static

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'productos', views.ProductoViewSet)
router.register(r'pagos', views.PagoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cakehouse/', include('cakehouse.urls')),
    path('api/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

caso/cakehouse/models.py
from django.db import models
from django.db.models.base import Model
from django.utils.translation import ugettext as _

# Create your models here.
class Producto(models.Model):
    nombre = models.CharField(max_length=100, default='')
    descripcion = models.CharField(max_length=100, default='')
    precio = models.IntegerField(default=0)
    stock = models.BooleanField(default=False)
    fecha = models.DateField('fecha de creacion')
    imagen = models.ImageField(upload_to ="productos",null=True)
    def __str__(self):
        return self.nombre

    class Meta:
        permissions = (
            ('gerente', _('Gerente cakehouse')),
        )

class Pago(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=70, default='')
    segundo_n = models.CharField(max_length=70, default='')
    apellido_p = models.CharField(max_length=70, default='')
    apellido_m = models.CharField(max_length=70, default='')
    direccion = models.CharField(max_length=70, default='')
    casa_dpto = models.CharField(max_length=70, default='')
    nro_casa = models.CharField(max_length=70, default='')
    email = models.CharField(max_length=70, default='')
    nro_telefono = models.CharField(max_length=70, default='')
    pago = models.IntegerField(default=0)

    def __str__(self):
        return self.nombre

    class Meta:
        permissions = (
            ('gerente', _('Gerente cakehouse')),
        )

caso/cakehouse/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render
from django.http import HttpResponse
from .models import Producto, Pago
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth import logout
from django.contrib import messages

# Create your views here.
def index(request):
    listado_productos = Producto.objects.all()
    carrito = {'listado_productos':listado_productos}
    return render(request,'cakehouse/index.html',carrito)

def ver_productos(request):
    pk=request.POST['pk']
    listado = Producto.objects.filter(id=pk)
    carrito = {"listado" : listado}
    return render(request,'cakehouse/ver_productos.html',carrito)

def pagar_productos(request):
    pk=request.POST['pk']
    listado = Producto.objects.filter(id=pk)
    carrito = {"listado" : listado}
    return render(request,'cakehouse/pagar_productos.html',carrito)

def guardar_pago(request):
    id = request.POST['id']
    nombre = request.POST['nombre']
    s_nombre = request.POST['s_nombre']
    apellido_p = request.POST['apellido_p']
    apellido_m = request.POST['apellido_m']
    direccion = request.POST['direccion']
    vivienda = request.POST['vivienda']
    if vivienda=="1":
        vivienda = "Casa"
    else:
        vivienda = "Departamento"
    numero_domi = request.POST['numero_domi']
    correo = request.POST['correo']
    numero_telefono = request.POST['numero_telefono']
    precio = request.POST['precio']
    producto = Producto.objects.get(id=id)
    pago = Pago(nombre=nombre,segundo_n=s_nombre,apellido_p=apellido_p,apellido_m=apellido_m,direccion=direccion,
    casa_dpto=vivienda,email=correo,nro_casa=numero_domi,nro_telefono=numero_telefono,pago=precio)
    pago.producto=producto
    pago.save()
    listado_productos = Producto.objects.all()
    messages.success(request,"compra realizada con exito")
    carrito = {'listado_productos':listado_productos}
    return render(request,'cakehouse/index.html',carrito)

def iniciosesion(request):
    return render(request, 'cakehouse/iniciosesion.html')

def inicses(request):
    usuario = request.POST['usuario']
    clave = request.POST['clave']

    user = authenticate(request, username=usuario, password=clave)


    if user is not None:
        login(request, user)
        return render(request,'cakehouse/indexadmin.html')
    else:
        listado_productos = Producto.objects.all()
        carrito = {'listado_productos':listado_productos}
        messages.success(request,"usted no cuenta con una cuenta de administrador")
        return render(request,'cakehouse/index.html',carrito)

def logoutv(request):
    logout(request)
    listado_productos = Producto.objects.all()
    carrito = {'listado_productos':listado_productos}
    return render(request,'cakehouse/index.html',carrito)

def indexadmin(request):
    listado_productos = Producto.objects.all()
    carrito = {'listado_productos':listado_productos}
    return render(request,'cakehouse/indexadmin.html',carrito)

caso/caso/views.py
from django.contrib.auth.models import User, Group
from rest_framework import viewsets
from rest_framework import permissions
from caso.serializers import UserSerializer, GroupSerializer, ProductoSerializer, PagoSerializer
from cakehouse.models import Producto, Pago


class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class GroupViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Group.objects.all()
    serializer_class = GroupSerializer
    permission_classes = [permissions.IsAuthenticated]

class ProductoViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Producto.objects.all()
    serializer_class = ProductoSerializer
    permission_classes = [permissions.IsAuthenticated]

class PagoViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Pago.objects.all()
    serializer_class = PagoSerializer
    permission_classes = [permissions.IsAuthenticated]

caso/cakehouse/templates/cakehouse/index.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/funciones.css' %}">
<body>
    <!-- navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
      <img src="{% static 'cakehouse/imagenes/cake.png' %}" alt="" />
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <p class="text-light" style="margin: 5px">
          Bienvenido a nuestra tienda Cake House, donde encontrarás nuestros
          sabrosos productos!<span class="sr-only">(current)</span>
        </p>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link text-light" href="{%url 'cakehouse:index'%}"
              >Home<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'cakehouse:iniciosesion'%}">Login admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'cakehouse:logoutv'%}">Cerrar sesión</a>
          </li>
        </ul>
      </div>
    </nav>
    {%if messages%}
      {%for m in messages%}
      <div class="alert alert-warning alert-dismissible fade show  mb-0" role="alert">
        <strong>MENSAJE!</strong>
        {{m}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      {%endfor%}

    {%endif%}
    <!--carrusel-->
    <header>
        <div
          id="carouselExampleCaptions"
          class="carousel slide"
          data-ride="carousel"
        >
          <ol class="carousel-indicators">
            <li
              data-target="#carouselExampleCaptions"
              data-slide-to="0"
              class="active"
            ></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img
                id="imagenes"
                src="{% static 'cakehouse/imagenes/carrusel1.jpg' %}"
                class="d-block w-100"
                alt="..."
              />
              <div
                class="
                  carousel-caption
                  d-none d-md-block
                  text-light
                  texto_carrusel
                "
              >
                <h5 class="txt_carrusel">Cupcakes</h5>
                <p class="txt_carrusel">Distintos y maravillosos sabores!</p>
              </div>
            </div>
            <div class="carousel-item imagen_carrusel">
              <img
                id="imagenes"
                src="{% static 'cakehouse/imagenes/carrusel2.jpg' %}"
                class="d-block w-100"
                alt="..."
              />
              <div
                class="
                  carousel-caption
                  d-none d-md-block
                  text-light
                  texto_carrusel
                "
              >
                <h5 class="txt_carrusel">Macarón Francés</h5>
                <p class="txt_carrusel">Gran variedad de colores y tamaños!</p>
              </div>
            </div>
          </div>
          <a
            class="carousel-control-prev"
            href="#carouselExampleCaptions"
            role="button"
            data-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a
            class="carousel-control-next"
            href="#carouselExampleCaptions"
            role="button"
            data-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </header>
{% if listado_productos %}
    <main id="contenedor_card">
        <div class="container">
            <div class="row justify-content-md-center pt-5 pb-5">
            {% for p in listado_productos %}
                <div class="col-sm-6 col-md-6 pt-4 pb-4">
                <div class="card cen">
{%if p.imagen %}
                    <img
                    id="img_card"
                    src="{{p.imagen.url}}"
                    class="card-img-top"
                    alt="..."
                    />
{%else%}
                    <img
                    id="img_card"
                    src=""
                    class="card-img-top"
                    alt="imagen no disponible"
                    />
{%endif%}
                    <div class="card-body bg-success text-light cuerpo_card">
                    <h5 class="card-title titulo">{{p.nombre}}</h5>
                    <p id="parrafo" class="card-text">
                        {{p.descripcion}}
                    </p>
                    <p class="card-text precio">Precio : ${{p.precio}} c/u</p>
                    <form action="{%url 'cakehouse:ver_productos'%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="pk" value="{{p.id}}">
                        <button class="btn btn-warning" type="submit">ver</button>
                    </form>
                    </div>
                </div>
                </div>
            {% endfor %}
            
        </div>
    </main>
{%endif%}
    <footer class="bg-success">
      <div>
        <p class="text-light" id="texto">
          Todos los derechos reservados Cake House©
          <span class="sr-only">(current)</span>
        </p>
      </div>
    </footer>    
    <script src="{% static 'cakehouse/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{%static 'cakehouse/js/bootstrap.bundle.min.js'%}"></script>
</body>

caso/cakehouse/templates/cakehouse/indexadmin.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/funciones.css' %}">
<body>
    <!-- navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
      <img src="{% static 'cakehouse/imagenes/cake.png' %}" alt="" />
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <p class="text-light" style="margin: 5px">
          Bienvenido a nuestra tienda Cake House, donde encontrarás nuestros
          sabrosos productos!<span class="sr-only">(current)</span>
        </p>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link text-light" href="http://127.0.0.1:8000/api/">API</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'cakehouse:logoutv'%}">Cerrar sesión</a>
          </li>
        </ul>
      </div>
    </nav>
    <!--carrusel-->
    <header>
        <div
          id="carouselExampleCaptions"
          class="carousel slide"
          data-ride="carousel"
        >
          <ol class="carousel-indicators">
            <li
              data-target="#carouselExampleCaptions"
              data-slide-to="0"
              class="active"
            ></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
            <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img
                id="imagenes"
                src="{% static 'cakehouse/imagenes/carrusel1.jpg' %}"
                class="d-block w-100"
                alt="..."
              />
              <div
                class="
                  carousel-caption
                  d-none d-md-block
                  text-light
                  texto_carrusel
                "
              >
                <h5 class="txt_carrusel">Cupcakes</h5>
                <p class="txt_carrusel">Distintos y maravillosos sabores!</p>
              </div>
            </div>
            <div class="carousel-item imagen_carrusel">
              <img
                id="imagenes"
                src="{% static 'cakehouse/imagenes/carrusel2.jpg' %}"
                class="d-block w-100"
                alt="..."
              />
              <div
                class="
                  carousel-caption
                  d-none d-md-block
                  text-light
                  texto_carrusel
                "
              >
                <h5 class="txt_carrusel">Macarón Francés</h5>
                <p class="txt_carrusel">Gran variedad de colores y tamaños!</p>
              </div>
            </div>
          </div>
          <a
            class="carousel-control-prev"
            href="#carouselExampleCaptions"
            role="button"
            data-slide="prev"
          >
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a
            class="carousel-control-next"
            href="#carouselExampleCaptions"
            role="button"
            data-slide="next"
          >
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </header>
{% if listado_productos %}
    <main id="contenedor_card">
        <div class="container">
            <div class="row justify-content-md-center pt-5 pb-5">
            {% for p in listado_productos %}
                <div class="col-sm-6 col-md-6 pt-4 pb-4">
                <div class="card cen">
                    <img
                    id="img_card"
                    src="img/cupcakes.jpg"
                    class="card-img-top"
                    alt="..."
                    />
                    <div class="card-body bg-success text-light cuerpo_card">
                    <h5 class="card-title titulo">{{p.nombre}}</h5>
                    <p id="parrafo" class="card-text">
                        {{p.descripcion}}
                    </p>
                    <p class="card-text precio">Precio : ${{p.precio}} c/u</p>
                    <form action="{%url 'cakehouse:ver_productos'%}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="nombre" value="{{p.nombre}}">
                        <input type="hidden" name="descripcion" value="{{p.descripcion}}">
                        <input type="hidden" name="precio" value="{{p.precio}}">
                        <button class="btn btn-warning" type="submit">ver</button>
                    </form>
                    </div>
                </div>
                </div>
            {% endfor %}
            
        </div>
    </main>

{%endif%}
    <footer class="bg-success">
      <div>
        <p class="text-light" id="texto">
          Todos los derechos reservados Cake House©
          <span class="sr-only">(current)</span>
        </p>
      </div>
    </footer>    
    <script src="{% static 'cakehouse/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{%static 'cakehouse/js/bootstrap.bundle.min.js'%}"></script>
</body>

caso/cakehouse/templates/cakehouse/pagar_productos.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/funciones3.css' %}">

<body style="background: burlywood;
height: 100vh;" class="cuerpo">
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
      <img src="{% static 'cakehouse/imagenes/cake.png' %}" alt="" />
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <p class="text-light" style="margin: 5px">
          Bienvenido a nuestra tienda Cake House, donde encontrarás nuestros
          sabrosos productos!<span class="sr-only">(current)</span>
        </p>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link text-light" href="{%url 'cakehouse:index'%}"
              >Home<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'cakehouse:iniciosesion'%}">Login admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'cakehouse:logoutv'%}">Cerrar sesión</a>
          </li>
        </ul>
      </div>
    </nav>
{%if listado%}
    <div class="container">
      <div class="py-2 text-center">
      {%for p in listado%}
{%if p.imagen%}
        <img
          class="d-block mx-auto mb-4 img-fluid"
          src="{{p.imagen.url}}"
          alt=""
          width="400px"
          height="400px"
        />
{%else%}
        <img
        class="d-block mx-auto mb-4 img-fluid"
        src=""
        alt="imagen no disponible"
        />
{%endif%}
        <h2>Compra de {{p.nombre}}</h2>
        {%endfor%}
{%endif%}
        <p class="lead pb-5">
          Obtenga beneficios por cada compra que realice, desde códigos de
          descuento hasta obtener las deseadas "yapas".
        </p>
      </div>
    </div>
    <form class="row g-3 m-3 contenedor" action="{%url 'cakehouse:guardar_pago'%}" method="POST">
    {% csrf_token %}
{%if listado%}
      {%for n in listado%}
      <input type="hidden" name="id" value="{{n.id}}" >
      {%endfor%}
{%endif%}
      <div class="col-md-3">
        <label for="" class="form-label">Nombre:</label>
        <input
          type="text"
          class="form-control"
          id=""
          required
          placeholder="Juan"
          name="nombre"
        />
      </div>
      <div class="col-md-3">
        <label for="" class="form-label">Segundo Nombre:</label>
        <input
          type="text"
          class="form-control"
          id=""
          required
          placeholder="Andrés"
          name="s_nombre"
        />
      </div>
      <div class="col-md-3">
        <label for="inputAddress" class="form-label">Apellido Paterno:</label>
        <input type="text" class="form-control" id="" required
        placeholder="López" 
        name="apellido_p"
        />
      </div>

      <div class="col-md-3">
        <label for="inputAddress2" class="form-label">Apellido Materno:</label>
        <input
          type="text"
          class="form-control"
          id=""
          required
          placeholder="Torres"
          name="apellido_m"
        />
      </div>
      <div class="col-md-3">
        <label for="" class="form-label">Dirección:</label>
        <input
          type="text"
          class="form-control"
          id=""
          required
          placeholder="Calle alta 19 sur"
          name="direccion"
        />
      </div>
      <div class="col-md-3">
        <label for="" class="form-label">Casa/depto</label>
        <div class="input-group mb-3">
          <div class="input-group-prepend">
            <label class="input-group-text" for="inputGroupSelect01">Vivienda</label>
          </div>
          <select name="vivienda" class="custom-select" id="inputGroupSelect01">
            <option selected>Escoja!</option>
            <option value="1">Casa</option>
            <option value="2">Departamento</option>
          </select>
        </div>
      </div>
      <div class="col-md-3">
        <label for="" class="form-label">Número de domicilio</label>
        <input
          type="text"
          class="form-control"
          id=""
          required
          placeholder="#1672"
          name="numero_domi"
        />
      </div>
      <div class="col-md-3">
{%if listado%}
        {%for m in listado%}
        <label for="" class="form-label">Valor a pagar</label>
        <input
          type="number"
          class="form-control"
          id=""
          required
          value="{{m.precio}}"
          
          disabled = "true"
        />
        <input type="hidden" name="precio" value="{{m.precio}}">
        {%endfor%}
{%endif%}
      </div>
      <div class="col-md-6">
        <label for="" class="form-label">Correo electrónico:</label>
        <input
          type="email"
          class="form-control"
          id=""
          required
          placeholder="correo@gmail.com"
          name="correo"
        />
      </div>
      <div class="col-md-6">
        <label for="" class="form-label">Número telefónico:</label>
        <input
          type="text"
          class="form-control"
          id=""
          required
          placeholder="+56921586479"
          name="numero_telefono"
        />
      </div>
      
      <button type="submit" class="btn btn-primary d-grid gap-2 col-6 mx-auto " id="boton"><img src="img/pagar.png" alt=""> Pagar</button>
    </form>
    

    <footer class="bg-success">
      <div>
        <p class="text-light" id="texto">
          Todos los derechos reservados Cake House©
          <span class="sr-only">(current)</span>
        </p>
      </div>
    </footer>
    <script src="{% static 'cakehouse/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{%static 'cakehouse/js/bootstrap.bundle.min.js'%}"></script>

</body>

caso/cakehouse/templates/cakehouse/ver_productos.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/funciones1.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cakehouse/estilos/funciones2.css' %}">
<body class="cuerpo">
    <!-- navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-success">
      <img src="{% static 'cakehouse/imagenes/cake.png' %}" alt="" />
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <p class="text-light" style="margin: 5px">
          Bienvenido a nuestra tienda Cake House, donde encontrarás nuestros
          sabrosos productos!<span class="sr-only">(current)</span>
        </p>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link text-light" href="{%url 'cakehouse:index'%}"
              >Home<span class="sr-only">(current)</span></a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'cakehouse:iniciosesion'%}">Login admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{%url 'cakehouse:logoutv'%}">Cerrar sesión</a>
          </li>
        </ul>
      </div>
    </nav>
{%if listado%}
    {%for p in listado%}
    <main style="margin-bottom: 30px;" id="productos">
        <div style="margin-bottom: 10px;" class="container-lg mb-4">
          <div class="row">
{%if p.imagen %}
            <img
              src="{{p.imagen.url}}"
              class="col-sm-12 col-lg-6 img_producto mt-5 "
              alt="..."
            />
{% else %}
            <img
            src=""
            class="col-sm-12 col-lg-6 img_producto mt-5 "
            alt="imagen no disponible"
            />
{%endif %}
            <div class="texto_producto col-sm-12 col-lg-6 mt-5 ">
                <h1 class="mt-0">{{p.nombre}}</h1>
                <h4 id="precio" class=" Precio">Precio ${{p.precio}} la unidad</h4>
                <h4>{{p.descripcion}}</h4>
                <h5>
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ex natus non, harum numquam reiciendis in debitis culpa asperiores repudiandae excepturi, ut eaque consequuntur corporis consequatur dolor optio aut sequi modi?
                </h5>
  
                <form action="{%url 'cakehouse:pagar_productos'%}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="pk" value="{{p.id}}">
                <button type="submit" class="btn btn-primary btn-lg boton">
                    Pedir
                </button>
                </form>
            </div>
          </div>
          <div  class="contenedor">
            <h3 id="detalle">detalle:</h3>
            <h5>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sed, minima facilis illo odio quos soluta esse libero repellendus at eos, culpa earum reprehenderit veritatis pariatur corporis dolor quas et sit.
          </div>
        </div>
    </main>
    {%endfor%}
{%endif%}
  <footer class="bg-success">
    <div>
      <p class="text-light" id="texto">
        Todos los derechos reservados Cake House©
        <span class="sr-only">(current)</span>
      </p>
    </div>
  </footer>  
    <script src="{% static 'cakehouse/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{%static 'cakehouse/js/bootstrap.bundle.min.js'%}"></script>

    
</body>